--- 
format: 1
handler: 
  commit: 8808fda3a4147908e2c1092815f39c988031c8b4
  branch: master
lock: false
repository_class: Piston::Git::Repository
repository_url: git://github.com/unclecheese/DataObjectManager.git
